title: Site

tabs:
  accueil:
    label: Accueil
    columns:
      main:
      - width: 1/3
        sections:
          pages:
            headline:
            type: pages
            template: 
              - atelier
              - devis
              - galerie
              - contact
              - mentions
            create: false
            layout: list
            sortable: true
            images: false
      - width: 2/3
        sections:
        fields:
          presentation:
            label: Présentation de l'atelier
            type: textarea
          image:
            label: Image
            type: files
            max: 1
            min: 1
            required: true
          contact_home:
              label: Email
              type: email
          networks:
            label: Réseaux
            type: structure
            fields:
              network:
                label: Nom du réseau
                type: text
                required: true
              link:
                label: Lien
                type: url
                required: true

  identite:
    label: Identité visuelle
    columns:
      main:
        width: 1/3
        sections:
          logo: 
            label: Logotype
            type: files
            max: 1
            min: 1