title: Site

options:
  changeStatus: false
  changeSlug: false
  delete: false

tabs:
  accueil:
    label: Accueil
    columns:
      main:
      - width: 2/3
        sections:
          pages:
            headline: Pages
            type: pages
            template: 
              - home
              - atelier
              - devis
              - galerie
              - contact
              - mentions
            create: true
            layout: list
            sortable: true
            images: false
  identite:
    label: Identité visuelle
    columns:
      main:
        width: 1/3
        sections:
          logo: 
            label: Logotype
            type: files
            max: 1
            min: 1