title: Site

options:
  changeStatus: false
  changeSlug: false
  delete: false

tabs:
  accueil:
    label: Accueil
    columns:
      main:
      - width: 2/3
        sections:
          pages:
            headline: Pages
            type: pages
            template: 
              - home
              - atelier
              - devis
              - devis-test
              - galerie
              - contact
              - mentions
              - redirection
            create: true
            layout: list
            sortable: true
            images: false
  identite:
    label: Identité visuelle
    columns:
      main:
        width: 1/3
        sections:
          logo: 
            label: Logotype
            type: files
            max: 1
            min: 1
            accept: 
              - image/svg+xml
              - image/png
              - image/jpeg

          # favicon: 
          #   label: Favicon
          #   type: files
          #   max: 1
          #   min: 1
          #   accept: 
          #     - image/svg+xml
          #     - image/png
          #     - image/jpeg